gems:
  - jekyll-sitemap
  - jekyll-mentions
safe: true
lsi: false
highlighter: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - highlighter
    - tables
exclude:
  - README.md
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss

navigation:
- title: Guide
  url: /guide/
- title: Upgrade
  url: /upgrade/
- title: FAQ
  url: /faq/
- title: About
  url: /about/
